name: mnb-image-analysis
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - jupyter
  - matplotlib
  - scipy
  - scikit-image
  - seaborn
  - pandas
  - ipympl
  - ipywidgets
  - tqdm
  - tifffile
  - pooch # For downloading cells3d dataset. Remove when we only use blobs
  - pip:
    - bioio
    - bioio-tifffile